### ISSUE TITLE
OOM Error

### ISSUE THREAD

**Issue by HamadYA** [ubc-vision/StableKeypoints#4]
Hi,

Thanks for the amazing work. I am encountering OOM error everytime I run the model. Any suggestions on what I can change to avoid this error?

**Comment by ehedlin** [comment]
To reduce vram usage I would recommend reducing `--num_tokens` from the default value of 500 or `--feature_upsample_res` from 128. 

To give more context for each of these, `--num_tokens` is essentially the capacity of the tokens to learn specific concepts. I found that higher always performed better but does end up taking a lot more memory. 

`--feature_upsample_res` is for determining the resolution of the attention maps. This increases the resolution of the queries and keys before performing cross attention. If you dont need the attention maps to be sharp you could reduce this. If you reduce this you might also want to increase the size of `--sigma` from 2 since this determines how 'sharp' the target attention map is.

**Comment by HamadYA** [comment]
> ining the resolution of the attention maps. This increases the resolution of the queries and keys before performing cross attention. If you dont need the attention maps to be sharp you could reduce this. If you reduce this you might also want to increase the size of `--sigma` from 2 since this determines how 'sharp' the target attention map is.

I tried to use:

--num_tokens = 1
--feature_upsample_res = 1
--sigma = 2

and I am still encountering OOM

When I use the CPU, it works normally with default values

**Comment by ehedlin** [comment]
This requires backpropagating through stable diffusion so is rather memory intensive. How much vram do you have? also `--num_tokens` should be at least 2.

**Comment by HamadYA** [comment]
> This requires backpropagating through stable diffusion so is rather memory intensive. How much vram do you have? also `--num_tokens` should be at least 2.

We are using aa workstation equipped with one Nvidia GeForce RTX 3080 GPU, 11th Gen Intel 2.3GHz CPU, 32GB RAM, and 8GB VRAM

**Comment by ehedlin** [comment]
I would recommend using the interactive [google colab](https://colab.research.google.com/drive/1ULz-HIR9LgzXL5Lr68Cn_HV4Fn6tMlBj?usp=sharing)

**Comment by HamadYA** [comment]
> I would recommend using the interactive [google colab](https://colab.research.google.com/drive/1ULz-HIR9LgzXL5Lr68Cn_HV4Fn6tMlBj?usp=sharing)

Thank you very much. Sorry for disturbing you in two issues.
I am planning to use your amazing work as a reference of mine.
I am closing this issue.

**Comment by HamadYA** [comment]
I apologize for this issue. One thing I did not notice is that there is an argument for image size (image_size=512).
Of course, when changing this to (256), the OOM error is mitigated.

Sorry I did not read the code carefully in the first time.

**Comment by ehedlin** [comment]
No worries. One thing to be careful about though is [stable diffusion version 1.5 was trained for 512x512 images](https://huggingface.co/CompVis/stable-diffusion-v1-1#training-procedure). I would make sure to check that attention maps for english words match the regions in the image they describe before building too much on this resolution.
